import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div data-theme="business" classNameName={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="hero min-h-screen">
        <div className="hero-overlay bg-opacity-60"></div>
        <div className="hero-content text-center text-neutral-content">
          <div className="max-w-md">
            <h1 className="mb-5 text-5xl font-extrabold">Redline Building Services</h1>
            <p className="mb-5">Provident cupiditate voluptatem et in. Quaerat fugiat ut assumenda excepturi exercitationem quasi. In deleniti eaque aut repudiandae et a id nisi.</p>
            <button className="btn btn-primary">Get Started</button>
          </div>
        </div>
      </div>

      <div>
        <div className="relative">
          <div className="fixed bottom-0 right-5 h-32 w-32">
            <label for="my-modal-4" className="btn btn-lg modal-button absolute border-white">open modal</label>
          </div>
        </div>

        <input type="checkbox" id="my-modal-4" className="modal-toggle" />
        <label for="my-modal-4" className="modal cursor-pointer">
          <label className="modal-box relative">
            <h3 className="text-lg font-bold">Congratulations random Interner user!</h3>
            <p className="py-4">You've been selected for a chance to get one year of subscription to use Wikipedia for free!</p>
          </label>
        </label>
      </div>

      <div className="services min-h-screen">
        
        <div className="grid grid-cols-1 place-items-center align-center p-4">
          <h1 className="mb-5 text-5xl font-extrabold align-center">Our Services</h1>
        </div>

        <div class="w-64 carousel rounded-box">
          <div class="carousel-item w-full">
            <div>
              <div className="card w-3/4 bg-base-100 shadow-xl place-items-center">
                <figure><img src="https://api.lorem.space/image/shoes?w=400&h=225" alt="Shoes" /></figure>
                <div className="card-body">
                  <h2 className="card-title">Shoes!</h2>
                  <p>If a dog chews shoes whose shoes does he choose?</p>
                </div>
              </div>
            </div>
          </div> 
          <div class="carousel-item w-full">
            <div>
              <div className="card w-3/4 bg-base-100 shadow-xl place-items-center">
                <figure><img src="https://api.lorem.space/image/shoes?w=400&h=225" alt="Shoes" /></figure>
                <div className="card-body">
                  <h2 className="card-title">Shoes!</h2>
                  <p>If a dog chews shoes whose shoes does he choose?</p>
                </div>
              </div>
            </div>
          </div> 
          <div class="carousel-item w-full">
            <div>
              <div className="card w-3/4 bg-base-100 shadow-xl place-items-center">
                <figure><img src="https://api.lorem.space/image/shoes?w=400&h=225" alt="Shoes" /></figure>
                <div className="card-body">
                  <h2 className="card-title">Shoes!</h2>
                  <p>If a dog chews shoes whose shoes does he choose?</p>
                </div>
              </div>
            </div>
          </div> 
          <div class="carousel-item w-full">
            <div>
              <div className="card w-3/4 bg-base-100 shadow-xl place-items-center">
                <figure><img src="https://api.lorem.space/image/shoes?w=400&h=225" alt="Shoes" /></figure>
                <div className="card-body">
                  <h2 className="card-title">Shoes!</h2>
                  <p>If a dog chews shoes whose shoes does he choose?</p>
                </div>
              </div>
            </div>
          </div> 
          <div class="carousel-item w-full">
            <div>
              <div className="card w-3/4 bg-base-100 shadow-xl place-items-center">
                <figure><img src="https://api.lorem.space/image/shoes?w=400&h=225" alt="Shoes" /></figure>
                <div className="card-body">
                  <h2 className="card-title">Shoes!</h2>
                  <p>If a dog chews shoes whose shoes does he choose?</p>
                </div>
              </div>
            </div>
          </div> 
          <div class="carousel-item w-full">
            <div>
              <div className="card w-3/4 bg-base-100 shadow-xl place-items-center">
                <figure><img src="https://api.lorem.space/image/shoes?w=400&h=225" alt="Shoes" /></figure>
                <div className="card-body">
                  <h2 className="card-title">Shoes!</h2>
                  <p>If a dog chews shoes whose shoes does he choose?</p>
                </div>
              </div>
            </div>
          </div> 
        </div>
      
      </div>

      <div className="contact min-h-screen">
        
      </div>

      {/* <footer classNameName={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span classNameName={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
